services:
  - type: web
    name: one-piece-bot
    env: node
    plan: free
    buildCommand: npm ci --production
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health
    disk:
      name: bot-data
      mountPath: /opt/render/project/data
      sizeGB: 1